services:
  frontend:
    user: node

    build:
      context: ./frontend
      dockerfile: Dockerfile

    restart: always

    volumes:
      - type: bind
        source: .
        target: /workspace

      - type: volume
        source: frontend-node-modules
        target: /workspace/frontend/node_modules

    networks:
      - metapaste_network
    ports:
      - 5173:5173
    depends_on:
      - backend

    command: sleep infinity


  backend:
    user: node

    build:
      context: ./backend
      dockerfile: Dockerfile

    restart: always

    volumes:
      - type: bind
        source: .
        target: /workspace

      - type: volume
        source: backend-node-modules
        target: /workspace/backend/node_modules

    networks:
      - metapaste_network
    ports:
      - 5200:5200

    command: sleep infinity

volumes:
  frontend-node-modules:
    name: frontend_node_modules
  backend-node-modules:
    name: backend_node_modules

networks:
  metapaste_network:
    name: metapaste_network
    driver: bridge
